import{a as g,i,S as h}from"./assets/vendor-f144e563.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&n(m)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const y="https://pixabay.com",L="/api/",w="44024733-f77ed4f0ed7e81c67856c8782";async function u(e,s=1,a=15){const n=`${y}${L}`;try{return(await g(n,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:a}})).data}catch(t){i.error({title:"Error",message:`Something went wrong. ${t.message}`})}}function v(e){return`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-item-image">
                <div class="info">
                    <p class="info-title">Likes:<span class="info-value">${e.likes}</span></p>
                    <p class="info-title">Views:<span class="info-value">${e.views}</span></p>
                    <p class="info-title">Comments:<span class="info-value">${e.comments}</span></p>
                    <p class="info-title">Downloads:<span class="info-value">${e.downloads}</span></p>
                </div>
            </a>
        </li>
    `}function f(e){return e.map(v).join("")}const r={form:document.querySelector(".search-form"),postsGallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more")};r.loader.classList.add("hidden");r.loadMoreBtn.classList.add("hidden");const p=new h(".gallery a");let l=1,c=0,d="";async function S(e){if(e.preventDefault(),r.postsGallery.innerHTML="",l=1,d=e.target.elements.searchQuery.value.trim(),!d){i.info({title:"No data",message:"Please enter a search query"});return}r.loader.classList.remove("hidden");try{const s=await u(d,l);c=s.totalHits,c===0&&(i.warning({title:"No result",message:"Sorry, there are no images matching your search query. Please try again!"}),r.loadMoreBtn.classList.add("hidden"));const a=f(s.hits);r.postsGallery.insertAdjacentHTML("beforeend",a),p.refresh(),c>15&&r.loadMoreBtn.classList.remove("hidden")}catch(s){i.error({title:"Error",message:`Something went wrong. ${s.message}`})}finally{r.loader.classList.add("hidden"),e.target.reset()}}r.form.addEventListener("submit",S);async function b(){l+=1,r.loader.classList.remove("hidden");try{const e=await u(d,l),s=f(e.hits);r.postsGallery.insertAdjacentHTML("beforeend",s),p.refresh();const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:n*2,behavior:"smooth"}),c=e.totalHits,c<=l*15&&(r.loadMoreBtn.classList.add("hidden"),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch(e){i.error({title:"Error",message:`Something went wrong. ${e.message}`})}finally{r.loader.classList.add("hidden")}}r.loadMoreBtn.addEventListener("click",b);
//# sourceMappingURL=commonHelpers.js.map
